Update security-report.yml

diff --git a/.github/workflows/security-report.yml b/.github/workflows/security-report.yml
--- a/.github/workflows/security-report.yml
+++ b/.github/workflows/security-report.yml
@@ -41,6 +41,17 @@ jobs:
     - name: Get Rate Limit 
       run: |
         curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" https://api.github.com/rate_limit
+
+    - name: List Report 
+      run: |
+        response=$(curl -s -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" https://api.github.com/repos/pratiksha2805-eng/EmployeeService/code-scanning/alerts)
+        if echo "$response" | grep -q "rate limit exceeded"; then
+          echo "Rate limit exceeded. Waiting for reset..."
+          sleep 3600  # Wait for 1 hour before retrying
+          exit 1
+        else
+          echo "$response" > security_report.json
+        fi
     
     - name: List Report 
       run: |
